_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
batch_size:
    value: 4
data:
    value: datasets/check/data.yaml
epochs:
    value: 10
img_size:
    value: 640
model:
    value: yolov8n.yaml
