_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 19
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
agnostic_nms:
    value: false
amp:
    value: true
augment:
    value: false
auto_augment:
    value: randaugment
batch:
    value: 8
box:
    value: 7.5
cache:
    value: false
cfg:
    value: null
classes:
    value: null
close_mosaic:
    value: 10
cls:
    value: 0.5
conf:
    value: 0.25
copy_paste:
    value: 0
cos_lr:
    value: false
crop_fraction:
    value: 1
data:
    value: datasets/new_dataset/split/data.yaml
degrees:
    value: 0
deterministic:
    value: true
device:
    value: null
dfl:
    value: 1.5
dnn:
    value: false
dropout:
    value: 0
dynamic:
    value: false
embed:
    value: null
epochs:
    value: 15
erasing:
    value: 0.4
exist_ok:
    value: false
fliplr:
    value: 0.5
flipud:
    value: 0
format:
    value: torchscript
fraction:
    value: 1
freeze:
    value: null
half:
    value: false
hsv_h:
    value: 0.015
hsv_s:
    value: 0.7
hsv_v:
    value: 0.4
imgsz:
    value: 640
int8:
    value: false
iou:
    value: 0.7
keras:
    value: false
kobj:
    value: 1
label_smoothing:
    value: 0
line_width:
    value: null
lr0:
    value: 0.01
lrf:
    value: 0.01
mask_ratio:
    value: 4
max_det:
    value: 300
mixup:
    value: 0
mode:
    value: predict
model:
    value: yolov8n.pt
momentum:
    value: 0.937
mosaic:
    value: 0
multi_scale:
    value: false
name:
    value: train5
nbs:
    value: 64
nms:
    value: false
opset:
    value: null
optimize:
    value: false
optimizer:
    value: auto
overlap_mask:
    value: true
patience:
    value: 50
perspective:
    value: 0
plots:
    value: true
pose:
    value: 12
prediction_configs:
    value:
        agnostic_nms: false
        amp: true
        augment: false
        auto_augment: randaugment
        batch: 8
        box: 7.5
        cache: false
        cfg: null
        classes: null
        close_mosaic: 10
        cls: 0.5
        conf: 0.25
        copy_paste: 0
        cos_lr: false
        crop_fraction: 1
        data: datasets/new_dataset/split/data.yaml
        degrees: 0
        deterministic: true
        device: null
        dfl: 1.5
        dnn: false
        dropout: 0
        dynamic: false
        embed: null
        epochs: 15
        erasing: 0.4
        exist_ok: false
        fliplr: 0.5
        flipud: 0
        format: torchscript
        fraction: 1
        freeze: null
        half: false
        hsv_h: 0.015
        hsv_s: 0.7
        hsv_v: 0.4
        imgsz: 640
        int8: false
        iou: 0.7
        keras: false
        kobj: 1
        label_smoothing: 0
        line_width: null
        lr0: 0.01
        lrf: 0.01
        mask_ratio: 4
        max_det: 300
        mixup: 0
        mode: predict
        model: yolov8n.pt
        momentum: 0.937
        mosaic: 0
        multi_scale: false
        name: train5
        nbs: 64
        nms: false
        opset: null
        optimize: false
        optimizer: auto
        overlap_mask: true
        patience: 50
        perspective: 0
        plots: true
        pose: 12
        pretrained: true
        profile: false
        project: null
        rect: false
        resume: false
        retina_masks: false
        save: false
        save_conf: false
        save_crop: false
        save_frames: false
        save_hybrid: false
        save_json: false
        save_period: -1
        save_txt: false
        scale: 0.5
        seed: 0
        shear: 0
        show: false
        show_boxes: true
        show_conf: true
        show_labels: true
        simplify: false
        single_cls: false
        source: null
        split: val
        stream_buffer: false
        task: detect
        time: null
        tracker: botsort.yaml
        translate: 0.1
        val: true
        verbose: true
        vid_stride: 1
        visualize: false
        warmup_bias_lr: 0
        warmup_epochs: 3
        warmup_momentum: 0.8
        weight_decay: 0.0005
        workers: 0
        workspace: 4
pretrained:
    value: true
profile:
    value: false
project:
    value: null
rect:
    value: false
resume:
    value: false
retina_masks:
    value: false
save:
    value: false
save_conf:
    value: false
save_crop:
    value: false
save_frames:
    value: false
save_hybrid:
    value: false
save_json:
    value: false
save_period:
    value: -1
save_txt:
    value: false
scale:
    value: 0.5
seed:
    value: 0
shear:
    value: 0
show:
    value: false
show_boxes:
    value: true
show_conf:
    value: true
show_labels:
    value: true
simplify:
    value: false
single_cls:
    value: false
source:
    value: null
split:
    value: val
stream_buffer:
    value: false
task:
    value: detect
time:
    value: null
tracker:
    value: botsort.yaml
translate:
    value: 0.1
val:
    value: true
verbose:
    value: true
vid_stride:
    value: 1
visualize:
    value: false
warmup_bias_lr:
    value: 0
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.8
weight_decay:
    value: 0.0005
workers:
    value: 0
workspace:
    value: 4
